import { Callout } from "../components/Callout";
import { DefinitionCard } from "../components/DefinitionCard";
import { ConceptCard } from "../components/ConceptCard";
import { InterviewQuestion } from "../components/InterviewQuestion";
import {
  Chip,
  Code,
  ComparisonTable,
  Formula,
  FlowDiagram,
  Grid,
  Panel,
  SubHeading,
  YesNo,
} from "../components/ui";
import { BiasVarianceLab } from "../components/viz/BiasVarianceLab";
import { OverfittingLab } from "../components/viz/OverfittingLab";
import { KFoldDiagram } from "../components/viz/KFoldDiagram";
import { SplitDiagram } from "../components/viz/diagrams";

/* ================================================================== */
/* 02 · ML Problem Types                                               */
/* ================================================================== */

export function ProblemTypes() {
  return (
    <>
      <Grid cols={2}>
        <ConceptCard
          title="Supervised Learning"
          priority="must"
          whatItIs={
            <>
              Learning a mapping <Code>x → y</Code> from examples where the correct answer{" "}
              <Code>y</Code> is provided.
            </>
          }
          intuition="You have a stack of worked examples with the answers on the back. The model's job is to learn the rule well enough to answer a card it has never seen."
          example="10 years of loan applications, each labelled defaulted / repaid. Train a model to score new applicants."
          keyTakeaway="Labels exist → supervised. The two flavours are classification (discrete label) and regression (continuous number)."
        />
        <ConceptCard
          title="Unsupervised Learning"
          priority="must"
          whatItIs="Finding structure in data that has no labels at all."
          intuition="Nobody tells you what the groups are. You're looking for patterns, density, or a lower-dimensional description that captures most of what's going on."
          example="Segmenting 2M customers into behavioural groups with K-Means, or compressing 200 features into 20 with PCA."
          keyTakeaway="No y column. Evaluation is the hard part — there's no ground truth to score against, so you fall back on internal metrics and human judgement."
        />
        <ConceptCard
          title="Semi-Supervised Learning"
          priority="important"
          whatItIs="Training on a small labelled set plus a large unlabelled set."
          intuition="Labelling is expensive; raw data is cheap. Use the shape of the unlabelled data to make the few labels you have go further."
          example="500 hand-labelled medical images plus 50,000 unlabelled ones. Train on the 500, pseudo-label the confident predictions on the rest, retrain."
          keyTakeaway="The practical answer to 'we can only afford to label 1% of our data'."
        />
        <ConceptCard
          title="Self-Supervised Learning"
          priority="must"
          tagline="how every modern foundation model is trained"
          whatItIs="Creating the supervision signal from the data itself — the labels are generated by hiding part of the input and asking the model to reconstruct it."
          intuition="No human labels the data, but the task is still 'predict this exact target', so the training machinery is ordinary supervised learning. The genius is that the target is free."
          example="Next-token prediction in an LLM; masked-patch reconstruction in an image model; contrastive learning where two crops of the same photo must land near each other in embedding space."
          keyTakeaway="Self-supervised = supervised training on labels the data generates for free. It's why pretraining scales: the label budget is infinite."
        />
      </Grid>

      <Callout variant="tip">
        For an <strong>AI Engineer</strong> role, self-supervised learning is the one to be crisp on. If you're
        asked "how was this LLM trained?", the answer starts "self-supervised next-token prediction on a large
        corpus, then supervised fine-tuning, then preference optimisation" — and the interviewer will usually pull
        on one of those threads.
      </Callout>

      <SubHeading priority="must">Classification vs Regression</SubHeading>
      <Grid cols={2}>
        <Panel title="Classification — discrete label">
          <ul className="bullet-list">
            <li><strong>Binary:</strong> spam / not spam, churn / stay, fraud / legitimate.</li>
            <li><strong>Multiclass:</strong> which of 10 digits; which of 5 product categories.</li>
            <li><strong>Multilabel:</strong> a photo can be <em>both</em> "beach" and "sunset" — labels are not mutually exclusive.</li>
            <li>Loss: cross-entropy / log loss. Metrics: precision, recall, F1, AUC.</li>
          </ul>
        </Panel>
        <Panel title="Regression — continuous number">
          <ul className="bullet-list">
            <li>House price, delivery ETA, expected revenue, demand forecast.</li>
            <li>Loss: MSE, MAE, Huber. Metrics: MAE, RMSE, R², MAPE.</li>
            <li>Ordinal targets (1–5 star rating) sit in between — often modelled either way depending on whether the gaps are meaningful.</li>
          </ul>
        </Panel>
      </Grid>

      <ComparisonTable
        headers={["Type", "Input", "Label", "Output example"]}
        rows={[
          ["Classification", "Email text + metadata", "spam / not spam", "P(spam) = 0.93 → flag it"],
          ["Regression", "House features (size, location, age)", "sale price in $", "$412,000"],
          ["Clustering", "Customer behaviour vectors", "none", "5 behavioural segments"],
          ["Dimensionality reduction", "200 sensor readings", "none", "20 components, 93% of variance kept"],
          ["Semi-supervised", "50k images, 500 labelled", "partial", "Classifier trained mostly on pseudo-labels"],
          ["Self-supervised", "Raw text corpus", "derived from the text", "Next-token distribution → an embedding model"],
          ["Reinforcement learning", "State of an environment", "reward signal", "A policy: which action to take next"],
        ]}
        caption="Reinforcement learning is a fourth paradigm — it learns from a reward signal rather than labelled examples. Worth one sentence in an interview, rarely more for an ML fundamentals round."
      />

      <Callout variant="mistake">
        Calling anything without a <Code>y</Code> column "unsupervised" and stopping there. Self-supervised
        learning also has no human labels, but it constructs targets and trains with a supervised objective — the
        distinction matters because it's the entire basis of modern pretraining.
      </Callout>

      <Callout variant="memorize" title="Real systems mix all of these">
        A production recommender is not one problem type. It typically has a{" "}
        <strong>self-supervised embedding model</strong> for items, an <strong>unsupervised</strong> nearest-neighbour
        index for candidate generation, a <strong>supervised</strong> ranking model for click probability, and a{" "}
        <strong>bandit / RL</strong> layer for exploration. Saying this out loud signals real system experience.
      </Callout>

      <SubHeading>Interview questions</SubHeading>
      <div className="space-y-2">
        <InterviewQuestion
          qa={{
            id: "pt1",
            q: "What is the difference between supervised and unsupervised learning?",
            short: "Supervised learning has target labels and learns a mapping from inputs to those labels; unsupervised learning has no labels and looks for structure in the inputs alone.",
            strong:
              "The practical difference is what you can evaluate. In supervised learning I have ground truth, so I can hold out data and measure error directly — accuracy, RMSE, AUC. In unsupervised learning there's nothing to compare against, so I'm relying on internal measures like inertia or silhouette score, plus whether the output is actually useful downstream. That's why unsupervised results are much harder to defend, and why I'd usually try to reframe a problem as supervised if any label signal exists.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "pt2",
            q: "Is anomaly detection supervised or unsupervised?",
            short: "It depends on whether you have labelled anomalies. Usually you don't, so it's unsupervised or semi-supervised — but if you do, it's just heavily imbalanced supervised classification.",
            strong:
              "It's framed three different ways depending on the labels available. With no labels, it's unsupervised: fit a density or distance model on the data and flag the tail — Isolation Forest, one-class SVM, autoencoder reconstruction error. With only normal examples labelled, it's semi-supervised novelty detection: model what normal looks like and flag deviations. With confirmed labelled anomalies, it's supervised binary classification with extreme class imbalance, and I'd reach for class weights and PR-AUC. In production these coexist — an unsupervised model bootstraps the system, analysts confirm cases, and those confirmations gradually turn it supervised.",
            deeper:
              "The trap in the unsupervised framing is that _rare_ and _anomalous_ are not the same thing. A rare-but-legitimate customer behaviour will be flagged by a density model just as readily as genuine fraud. Precision at the top of the ranking is usually the metric that matters, because the alert queue has a fixed human capacity.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "pt3",
            q: "Is recommendation a classification problem?",
            short: "It can be modelled that way — predict click / no-click per item — but at its core it's a ranking problem, and framing it purely as classification loses the thing you care about.",
            strong:
              "The common production framing is two-stage. Retrieval narrows millions of items to a few hundred candidates, usually with embeddings and approximate nearest neighbour search — that part is closer to self-supervised representation learning than classification. Then ranking scores those candidates, and that stage often is a binary classifier on click or conversion. But the objective I actually care about is the ordering of the top-K, so I'd evaluate with NDCG, MAP or recall@K rather than accuracy. Treating it as plain classification also ignores the feedback loop: the model's own recommendations determine what data you collect next.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "pt4",
            q: "How would you decide between framing something as classification or regression?",
            short: "Ask what decision the output drives. If the action is a threshold on a category, classify. If the magnitude itself is used, regress.",
            strong:
              "I start from the decision downstream. If someone's going to act on 'is this over the line or not', classification with a calibrated probability gives me a threshold I can tune to business cost. If the number itself feeds into something — pricing, capacity planning, an expected-value calculation — regression is the right frame, because bucketing throws away information I'd have to reconstruct. One caveat: predicting a continuous value and then thresholding it is often worse than classifying directly, because regression loss spends its capacity being accurate in ranges nobody cares about.",
          }}
        />
      </div>
    </>
  );
}

/* ================================================================== */
/* 03 · Train / Validation / Test                                      */
/* ================================================================== */

export function Splits() {
  return (
    <>
      <ConceptCard
        title="The three splits"
        priority="must"
        whatItIs="Partition the data into a set the model learns from, a set you make decisions on, and a set that is opened exactly once to estimate real-world performance."
        intuition="Training data is the homework, validation data is the practice exam you can retake, and the test set is the real exam. If you keep retaking the real exam until you like your score, the score stops meaning anything."
        keyTakeaway="Train = fit parameters. Validation = choose hyperparameters and models. Test = one final, honest number."
      />

      <SplitDiagram />

      <SubHeading priority="must">Why the test set must stay sealed</SubHeading>
      <DefinitionCard term="The mechanism">
        Every time you look at the test score and change something in response — a hyperparameter, a feature, the
        model family, even the decision to keep training — you are <strong>fitting to the test set through your
        own decisions</strong>. Nothing in the code touched it, but information flowed from it into your model. After
        twenty such decisions the test score is no longer an unbiased estimate; it has quietly become a second
        validation score, and the optimism it carries is invisible because you have nothing left to check it against.
      </DefinitionCard>

      <Grid cols={2}>
        <Panel title="What validation data is for" tone="green">
          <ul className="bullet-list">
            <li>Comparing model families (GBM vs logistic regression).</li>
            <li>Choosing hyperparameters (depth, learning rate, λ).</li>
            <li>Early stopping — when to stop adding trees or epochs.</li>
            <li>Picking the decision threshold.</li>
            <li>Feature selection decisions.</li>
          </ul>
          <p className="mt-2">
            Because you look at it repeatedly, the validation score is <em>also</em> optimistic. That's expected —
            that's precisely why the test set exists.
          </p>
        </Panel>
        <Panel title="Rules of thumb for sizing" tone="neutral">
          <ul className="bullet-list">
            <li>
              Size the validation/test sets by <strong>absolute count, not percentage</strong>. What matters is
              having enough positives for the metric to be stable.
            </li>
            <li>
              With 10M rows, 1% is a 100k test set — plenty. Going to 20% just wastes 1.9M training rows.
            </li>
            <li>
              With 2,000 rows, a 10% test set is 200 rows — a single metric point has an error bar of several
              percent. Use cross-validation and report the spread.
            </li>
            <li>
              Rare positive class? Count the positives, not the rows. 10,000 test rows at 0.3% positive is only 30
              positives; recall will swing wildly.
            </li>
          </ul>
        </Panel>
      </Grid>

      <SubHeading priority="must">Three ways to split, and when each is wrong</SubHeading>
      <ComparisonTable
        headers={["Strategy", "How it works", "Use when", "Breaks when"]}
        rows={[
          [
            "Random",
            "Shuffle rows, cut.",
            "Rows are independent and identically distributed; no time dimension.",
            "There's a time order, grouped/duplicate entities, or a rare class.",
          ],
          [
            "Stratified",
            "Shuffle within each class so every split keeps the same class ratio.",
            "Classification, especially with imbalance or a small dataset.",
            "Rarely wrong for classification — it's the sensible default.",
          ],
          [
            "Time-based",
            "Train on everything before a cutoff, validate after it.",
            "Any target that depends on time: forecasting, churn, fraud, pricing, ranking.",
            "Never wrong for temporal data — random splitting here is a leakage bug.",
          ],
          [
            "Group / entity",
            "All rows for one user, patient or device go to exactly one split.",
            "Repeated measurements of the same entity.",
            "Skipping it lets the model recognise the entity instead of the pattern.",
          ],
        ]}
      />

      <Callout variant="mistake" title="When random splitting is flat-out wrong">
        <ul className="bullet-list">
          <li>
            <strong>Time series.</strong> A random split trains on next month and tests on last month. Your model
            gets to see the future, and the score is meaningless.
          </li>
          <li>
            <strong>Grouped data.</strong> 50 sessions per user, split randomly → the same user is in train and
            test. You're measuring memorisation of users, not generalisation to new users.
          </li>
          <li>
            <strong>Near-duplicates.</strong> Scraped datasets, augmented images, re-posted text. Identical content
            on both sides of the split inflates every number.
          </li>
        </ul>
      </Callout>

      <SubHeading>Interview questions</SubHeading>
      <div className="space-y-2">
        <InterviewQuestion
          qa={{
            id: "sp1",
            q: "Why can't we tune hyperparameters using the test set?",
            short: "Because then the test score measures how well you fitted the test set, not how well the model generalises. You'd have no clean estimate left.",
            strong:
              "Hyperparameter tuning is a search: you try configurations and keep the one that scores best. Whatever data you score against, you're optimising against — so its score becomes optimistically biased by the search itself. If I tune on the test set, the reported number includes that optimism and I have nothing held back to detect it. The whole point of the third split is to have one dataset that never influenced a single decision, so the final number is an unbiased estimate of production performance. Practically: tune on validation or cross-validation folds, then touch the test set once.",
            deeper:
              "This is the multiple-comparisons problem. Evaluate 100 random configurations on a validation set of 1,000 rows and the best one is beating the others partly on genuine merit and partly on noise. The expected gap between validation and true performance grows with the number of configurations tried — which is also why a huge random search on a small dataset can make things _worse_.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "sp2",
            q: "You have 800 labelled rows. How do you split them?",
            short: "Don't use a three-way split. Hold out ~20% as a test set and use stratified k-fold cross-validation on the remaining 80% for every tuning decision.",
            strong:
              "At 800 rows a 10% validation set is 80 rows, and a single accuracy figure from 80 rows has an error bar of several percentage points — I'd be tuning on noise. So I'd take a stratified 20% test set, about 160 rows, and run stratified 5-fold CV inside the remaining 640 for model selection. I'd report the CV mean and standard deviation, not just the mean, because at this size the spread is the honest part of the answer. And I'd be sceptical of any improvement smaller than that spread.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "sp3",
            q: "Your test accuracy is much lower than your validation accuracy. What happened?",
            short: "Most likely you over-tuned on the validation set, or the two sets aren't drawn from the same distribution.",
            strong:
              "Two families of cause. First, overfitting the validation set: if I ran a large hyperparameter search against one fixed validation split, the winning configuration is partly fitted to that split's noise and the drop to test is the correction. Cross-validation instead of a single split fixes that. Second, a distribution mismatch: if the split was random but the data is temporal, or the test set came from a different segment, source or time window, then the two sets genuinely aren't measuring the same thing. I'd check the split logic and compare feature distributions between the two before touching the model.",
          }}
        />
      </div>
    </>
  );
}

/* ================================================================== */
/* 04 · Data Leakage                                                   */
/* ================================================================== */

export function DataLeakage() {
  return (
    <>
      <Callout variant="warning" title="Why this section gets its own box">
        Leakage is the most commonly asked <em>practical</em> ML question and the most common real-world failure.
        A leaking model doesn't look broken — it looks <strong>excellent</strong>. That's what makes it dangerous:
        the failure signal is a suspiciously good score, and the instinct is to celebrate it.
      </Callout>

      <ConceptCard
        title="Data Leakage"
        priority="must"
        whatItIs="Information reaches the model during training that would not be available at prediction time in production — so offline scores are inflated and the model underdelivers when deployed."
        intuition="It's an exam where a few answers were accidentally printed in the question paper. The student scores 98%, learns nothing, and fails the next exam."
        example="You predict 30-day churn and one of your features is `support_tickets_last_30_days`, computed over the same window as the label. Cancelling customers file tickets. AUC 0.97 offline; in production, at the moment of scoring, that window hasn't happened yet."
        interviewAnswer="Leakage is when a feature encodes information about the target that wouldn't exist at inference time. The tell is a metric that's too good — if I see AUC jump from 0.78 to 0.96 after adding a feature, my first assumption is leakage, not a breakthrough. I'd check feature importance, look at what the top feature actually is, and ask when it becomes known relative to the prediction timestamp."
        commonMistake="Thinking of leakage as only 'the target got into the features'. Most real leakage is subtler: preprocessing statistics computed over the whole dataset, or a time window that straddles the prediction point."
        keyTakeaway="Ask one question of every feature: would this value exist, with this value, at the moment I need to predict? If not, it leaks."
      />

      <SubHeading priority="must">The preprocessing trap</SubHeading>
      <Grid cols={2}>
        <div className="card overflow-hidden">
          <div className="border-b border-rose-300 bg-rose-50 px-4 py-2 text-[11px] font-bold uppercase tracking-[0.09em] text-rose-700 dark:border-rose-400/30 dark:bg-rose-500/10 dark:text-rose-300">
            ✕ Wrong
          </div>
          <div className="p-4">
            <FlowDiagram
              steps={[
                { label: "Full dataset", tone: "red" },
                { label: "Normalize / impute / encode", note: "statistics computed over every row", tone: "red" },
                { label: "Split into train / test", tone: "red" },
              ]}
            />
            <p className="mt-3 text-[0.86rem] leading-relaxed text-muted">
              The scaler's mean and standard deviation were computed using test rows. Every training row now
              carries a whisper of the test set. The test score is optimistic and you cannot tell by how much.
            </p>
          </div>
        </div>

        <div className="card overflow-hidden">
          <div className="border-b border-emerald-300 bg-emerald-50 px-4 py-2 text-[11px] font-bold uppercase tracking-[0.09em] text-emerald-700 dark:border-emerald-400/30 dark:bg-emerald-500/10 dark:text-emerald-300">
            ✓ Right
          </div>
          <div className="p-4">
            <FlowDiagram
              steps={[
                { label: "Full dataset", tone: "green" },
                { label: "Split first", tone: "green" },
                { label: "fit_transform() on train only", note: "learn the statistics here", tone: "green" },
                { label: "transform() on val / test", note: "apply the frozen statistics", tone: "green" },
              ]}
            />
            <p className="mt-3 text-[0.86rem] leading-relaxed text-muted">
              The test set is treated exactly as production data will be: transformed by parameters it had no say
              in producing.
            </p>
          </div>
        </div>
      </Grid>

      <DefinitionCard term="fit_transform vs transform — say it precisely">
        <p className="mb-2">
          <Code>fit()</Code> <strong>learns parameters</strong> from data — the mean and standard deviation for a
          scaler, the category list for an encoder, the median for an imputer, the components for PCA.{" "}
          <Code>transform()</Code> <strong>applies</strong> already-learned parameters.
        </p>
        <Formula>{`# train
X_train_s = scaler.fit_transform(X_train)   # learns mean/std HERE

# validation and test
X_val_s   = scaler.transform(X_val)         # reuses train mean/std
X_test_s  = scaler.transform(X_test)        # reuses train mean/std`}</Formula>
        <p className="mt-2">
          In production there <em>is</em> no test set — you get one row at a time. Calling{" "}
          <Code>fit</Code> on it would be meaningless. That's the cleanest way to explain why the rule exists.
        </p>
      </DefinitionCard>

      <SubHeading priority="must">The leakage catalogue</SubHeading>
      <ComparisonTable
        headers={["Leak", "What it looks like", "Fix"]}
        rows={[
          [
            "Preprocessing before split",
            "Scaling, imputation, encoding or PCA fitted on the full dataset.",
            "Split first. Wrap every step in a Pipeline so fitting can only ever see training folds.",
          ],
          [
            "Target leakage",
            "A feature derived from, or only available because of, the outcome — `total_paid` when predicting default, `discharge_code` when predicting readmission.",
            "Audit the top features by importance. For each, ask when its value becomes known.",
          ],
          [
            "Future information",
            "Aggregates computed over a window that extends past the prediction timestamp.",
            "Compute every feature as of the prediction time. Time-based splits, and point-in-time correct joins.",
          ],
          [
            "Duplicate / near-duplicate rows",
            "The same user, image or document in both train and test.",
            "Deduplicate before splitting; use GroupKFold on the entity id.",
          ],
          [
            "Group leakage",
            "Multiple rows per patient/user split randomly across train and test.",
            "Split by group, never by row.",
          ],
          [
            "Target encoding without folds",
            "Category means computed on all rows, including the row being encoded.",
            "Out-of-fold target encoding, plus smoothing.",
          ],
          [
            "Oversampling before split",
            "SMOTE applied to everything, so synthetic copies of test positives end up in training.",
            "Resample inside the training fold only, never before splitting or before CV.",
          ],
          [
            "Feature selection on all data",
            "Picking the top-k features by correlation with y over the whole dataset.",
            "Selection is a fitted step — do it inside the CV loop.",
          ],
        ]}
      />

      <Callout variant="memorize" title="The one-line detector">
        Any step that <strong>learns something from data</strong> — a mean, a median, a category list, a component,
        a selected feature set, a synthetic sample — must be fitted <strong>inside</strong> the training fold. If you
        can put it in a <Code>Pipeline</Code>, you have made the mistake structurally impossible, which is the answer
        interviewers are hoping to hear.
      </Callout>

      <SubHeading>Interview questions</SubHeading>
      <div className="space-y-2">
        <InterviewQuestion
          qa={{
            id: "dl1",
            q: "What is data leakage and how would you detect it?",
            short: "Information available at training time that won't be available at prediction time. The main tell is performance that's implausibly good.",
            strong:
              "Detection is mostly discipline plus suspicion. First, suspicion: if a model hits 0.98 AUC on a problem where the business baseline is 0.75, I assume leakage before I assume success. Second, feature importance: I look at the top few features and ask, for each one, when its value is actually known relative to the prediction timestamp. Third, the split: I check that preprocessing is inside a pipeline, that the split respects time and entity grouping, and that there are no duplicate ids across splits. Fourth, the strongest test — if I can, I evaluate on a genuinely later time period. Leakage almost always collapses under a temporal holdout.",
            deeper:
              "A useful trick is a **leakage ablation**: drop the single most important feature and retrain. If performance falls off a cliff — 0.96 to 0.72 — that feature is doing something no legitimate signal should be able to do on its own, and it deserves a hard look.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "dl2",
            q: "Why is it wrong to scale before splitting? The mean barely changes.",
            short: "Because it makes the test score biased, and the size of the bias is unknown. The point isn't the magnitude, it's that the estimate is no longer clean.",
            strong:
              "On a large dataset with a StandardScaler, the practical effect is genuinely tiny — the mean and standard deviation barely move. But two things make it worth being strict about. First, the test set stops being an honest simulation of production, and once you accept 'a little leakage', you've lost the argument for excluding the more damaging kinds. Second, the same mistake with a different transform is severe: fitting PCA, a target encoder, a feature selector or SMOTE on the full dataset can move a score by many points. It's much easier to hold a blanket rule — everything fitted goes inside the pipeline — than to reason case by case about which leaks are small.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "dl3",
            q: "You add a feature and AUC jumps from 0.79 to 0.97. What do you do?",
            short: "Assume leakage and investigate before telling anyone the good news.",
            strong:
              "A jump that size on a real problem is almost never a modelling win. I'd trace the feature back to its source and establish exactly when its value is written relative to the moment I need a prediction. Very often it's populated by a downstream process that only runs after the outcome is known. I'd also check whether it's a near-copy of the label — grouping the target by that feature usually makes it obvious. If the feature genuinely is available at prediction time, then I'd validate on a later time window before believing it.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "dl4",
            q: "How does cross-validation interact with leakage?",
            short: "CV amplifies it. If preprocessing is fitted outside the CV loop, every fold is contaminated and the CV score looks great across the board.",
            strong:
              "The dangerous property of leakage under CV is that it's consistent — every fold leaks the same way, so you get a tight, confident, completely wrong estimate. The low variance actively reassures you. The fix is structural: put every fitted step inside a Pipeline and pass the pipeline to cross_val_score, so scikit-learn refits the preprocessing on each training fold. And pick the CV splitter to match the data — StratifiedKFold for imbalance, GroupKFold for repeated entities, TimeSeriesSplit for anything temporal.",
          }}
        />
      </div>
    </>
  );
}

/* ================================================================== */
/* 05 · Overfitting and Underfitting                                   */
/* ================================================================== */

export function OverUnderfitting() {
  return (
    <>
      <Grid cols={2}>
        <ConceptCard
          title="Underfitting"
          priority="must"
          tagline="high bias"
          whatItIs="The model is too simple, or too constrained, to capture the real pattern — so it performs badly on training data and equally badly on validation data."
          intuition="You tried to draw a straight line through something curved. No amount of extra data helps, because the model can't express the shape in the first place."
          example="Plain linear regression on a target that depends on an interaction between two features. Train R² = 0.31, validation R² = 0.29."
          keyTakeaway="Both scores bad, and close together → underfitting. The model is the bottleneck, not the data."
        />
        <ConceptCard
          title="Overfitting"
          priority="must"
          tagline="high variance"
          whatItIs="The model has learned the noise and quirks of this particular training sample rather than the pattern that generalises — excellent on training data, notably worse on unseen data."
          intuition="Memorising the answers to last year's exam. Perfect on those questions, lost on new ones."
          example="An unpruned decision tree: 100% train accuracy, 71% validation accuracy. It carved out a leaf for practically every training row."
          keyTakeaway="Train score much better than validation score → overfitting. The gap is the diagnosis."
        />
      </Grid>

      <OverfittingLab />

      <SubHeading priority="must">Diagnose from two numbers</SubHeading>
      <ComparisonTable
        headers={["Train score", "Validation score", "Diagnosis", "First move"]}
        rows={[
          ["Low", "Low (similar)", <span key="a" className="font-bold text-amber-600 dark:text-amber-400">Underfitting / high bias</span>, "More capacity, better features, train longer, less regularization"],
          ["High", "Much lower", <span key="b" className="font-bold text-rose-600 dark:text-rose-400">Overfitting / high variance</span>, "More data, more regularization, simpler model, early stopping"],
          ["High", "High (similar)", <span key="c" className="font-bold text-emerald-600 dark:text-emerald-400">Good fit</span>, "Ship it — then check the test set once"],
          ["Low", "High", <span key="d" className="font-bold text-violet-600 dark:text-violet-400">Something is wrong</span>, "Broken split, leakage into validation, or dropout/augmentation active only at train time"],
        ]}
        caption="That last row surprises people. In neural networks it's often benign — dropout and augmentation are on during training and off during evaluation, so training loss can legitimately look worse. Otherwise, check your split."
      />

      <SubHeading priority="must">Fix lists</SubHeading>
      <Grid cols={2}>
        <Panel title="Reduce overfitting" tone="red">
          <ul className="bullet-list">
            <li><strong>More training data</strong> — the most reliable fix, and usually the least available.</li>
            <li><strong>Regularization</strong> — L1/L2 penalties, weight decay, higher λ.</li>
            <li><strong>Simpler model</strong> — shallower trees, fewer parameters, lower polynomial degree.</li>
            <li><strong>Early stopping</strong> — halt when validation loss stops improving.</li>
            <li><strong>Dropout</strong> (neural networks) — randomly zero activations so no unit becomes load-bearing.</li>
            <li><strong>Data augmentation</strong> — flips, crops, noise, paraphrases: more effective variety for free.</li>
            <li><strong>Bagging / ensembling</strong> — averaging independent models cancels sample-specific error.</li>
            <li><strong>Feature reduction</strong> — fewer, better features; drop the noise columns.</li>
            <li><strong>Cross-validation</strong> — doesn't reduce overfitting, but it stops you from being fooled about it.</li>
          </ul>
        </Panel>
        <Panel title="Reduce underfitting" tone="green">
          <ul className="bullet-list">
            <li><strong>More expressive model</strong> — deeper trees, boosting instead of a single tree, a kernel instead of a linear boundary.</li>
            <li><strong>Better features</strong> — interactions, ratios, domain-derived signals. Usually the biggest lever on tabular data.</li>
            <li><strong>Train longer</strong> — more epochs, more boosting rounds; check the loss is still falling.</li>
            <li><strong>Less regularization</strong> — lower λ, less dropout, higher max depth.</li>
            <li><strong>Higher learning rate or better optimizer</strong> if training simply hasn't converged.</li>
            <li><strong>Check for a bug</strong> — persistent underfitting on an easy problem often means broken features, a scrambled target, or a label bug.</li>
          </ul>
        </Panel>
      </Grid>

      <Callout variant="mistake">
        "More data fixes overfitting" is true; "more data fixes underfitting" is not. If the model can't represent
        the pattern, ten times the data gets you a very confident straight line through a curve.
      </Callout>

      <Callout variant="tip" title="What a strong answer sounds like">
        Don't just define the two words. Say how you'd <em>detect</em> it — "I'd compare training and validation
        curves; a widening gap as training progresses means overfitting, both curves flat and high means
        underfitting" — and then name two or three fixes with a reason for each. Interviewers are checking whether
        you've actually debugged a model, not whether you've read the definition.
      </Callout>
    </>
  );
}

/* ================================================================== */
/* 06 · Bias–Variance                                                  */
/* ================================================================== */

export function BiasVariance() {
  return (
    <>
      <ConceptCard
        title="The decomposition"
        priority="must"
        whatItIs={
          <>
            Expected prediction error splits into three parts:{" "}
            <strong>bias²</strong> (error from wrong assumptions), <strong>variance</strong> (error from
            sensitivity to the particular training sample), and <strong>irreducible error</strong> (noise you can
            never model away).
          </>
        }
        intuition="Bias is being consistently wrong in the same direction. Variance is being wrong in a different direction every time you retrain on new data. You can trade one for the other, but you cannot remove the noise floor."
        keyTakeaway="Bias = wrong on average. Variance = unstable across samples. Total error = bias² + variance + noise."
      >
        <Formula caption="Expected squared error at a point x, averaged over training sets.">
          {`E[(y − f̂(x))²]  =  Bias[f̂(x)]²  +  Var[f̂(x)]  +  σ²
                          ↑              ↑            ↑
                    wrong on avg    unstable      irreducible`}
        </Formula>
      </ConceptCard>

      <BiasVarianceLab />

      <ComparisonTable
        headers={["", "High bias", "High variance"]}
        rows={[
          ["Also called", "Underfitting", "Overfitting"],
          ["Training error", "High", "Very low"],
          ["Validation error", "High, close to training", "Much higher than training"],
          ["Retrain on a new sample", "You get almost the same model", "You get a noticeably different model"],
          ["Typical culprits", "Linear model on nonlinear data · too much regularization · too few features", "Deep unpruned tree · tiny dataset · too many features · high-degree polynomial"],
          ["More data helps?", <YesNo key="a" v="no" />, <YesNo key="b" v="yes" />],
          ["Standard fixes", "More capacity, better features, less regularization", "More data, more regularization, simpler model, bagging"],
        ]}
      />

      <Grid cols={2}>
        <Callout variant="example" title="High bias in the wild">
          Linear regression on housing prices where price depends on <Code>size × neighbourhood_quality</Code>. The
          model can only add the two effects, never multiply them, so it's systematically wrong on both cheap
          small homes and expensive large ones. Refitting on a different sample of houses gives you almost exactly
          the same wrong line — that's the signature of bias.
        </Callout>
        <Callout variant="example" title="High variance in the wild">
          A decision tree grown to full depth on 500 rows. It reaches 100% training accuracy by creating a leaf per
          row. Resample the 500 rows and you get a structurally different tree with different predictions.
          Averaging 500 such trees — a random forest — is exactly how you cash in on that instability.
        </Callout>
      </Grid>

      <Callout variant="memorize" title="The relationship to recite">
        <div className="grid gap-2 sm:grid-cols-2">
          <Formula>{`complexity ↑   →   bias ↓ , variance ↑
complexity ↓   →   bias ↑ , variance ↓`}</Formula>
          <Formula>{`regularization ↑  →  bias ↑ , variance ↓
more data         →  variance ↓ , bias ≈ same`}</Formula>
        </div>
      </Callout>

      <SubHeading>Interview questions</SubHeading>
      <div className="space-y-2">
        <InterviewQuestion
          qa={{
            id: "bv1",
            q: "What happens to bias and variance as model complexity increases?",
            short: "Bias falls, variance rises. Total error is U-shaped — it falls until the variance increase overtakes the bias reduction, then climbs.",
            strong:
              "A more flexible model can represent more functions, so its systematic error — bias — goes down. But it also has more freedom to fit whatever happens to be in this particular training sample, so it becomes more sensitive to which rows it saw, and that's variance going up. Total expected error is the sum, plus an irreducible noise term, so it traces a U. The minimum of that U is what hyperparameter tuning is searching for. In practice I find it empirically: sweep the complexity knob and watch where validation error bottoms out.",
            deeper:
              "The classical U-shape isn't the whole story. Very heavily over-parameterised models — large neural networks — often show **double descent**: test error rises to a peak around the interpolation threshold and then falls again as capacity keeps growing. It's worth knowing the term exists, but for a fundamentals round the U-shaped story is the expected answer.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "bv2",
            q: "Can you have high bias and high variance at the same time?",
            short: "Yes. A badly specified model that's also unstable — the worst of both.",
            strong:
              "They're separate quantities, not two ends of one dial. A shallow tree on poorly chosen features can be both systematically wrong and unstable across resamples. It's less common than the classic tradeoff because most modelling choices move both at once in opposite directions, but it does show up — typically when the features are wrong. That's the useful insight: if you're stuck with high bias and high variance, the problem is usually upstream of the model.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "bv3",
            q: "How do bagging and boosting map onto bias and variance?",
            short: "Bagging mainly reduces variance; boosting mainly reduces bias — and both can overfit if pushed too far.",
            strong:
              "Bagging trains many high-variance, low-bias models on bootstrap samples and averages them. Averaging shrinks the variance of the ensemble without changing the bias much — that's why random forests use deep, unpruned trees. Boosting goes the other way: it starts from weak, high-bias learners like depth-3 stumps and adds them sequentially, each fitting the current residuals, so the ensemble's bias falls with every round. The catch is that boosting will happily keep reducing training error past the point of usefulness, so it needs early stopping and a small learning rate. Random forests are much harder to overfit by adding trees.",
          }}
        />
      </div>
    </>
  );
}

/* ================================================================== */
/* 08 · Cross-Validation                                               */
/* ================================================================== */

export function CrossValidation() {
  return (
    <>
      <ConceptCard
        title="K-Fold Cross-Validation"
        priority="must"
        whatItIs="Split the training data into K equal folds. Train K times, each time holding out a different fold for evaluation, and average the K scores."
        intuition="One train/validation split gives you one noisy score that depends heavily on which rows happened to land in validation. K-fold gives you K scores, so you get both a better estimate and a measure of how much it wobbles."
        example="5-fold CV on 1,000 rows: five models, each trained on 800 and scored on a different 200. Report 0.847 ± 0.019."
        interviewAnswer="Cross-validation reuses the data efficiently — every row is used for validation exactly once and for training K−1 times — so I get a lower-variance estimate of generalisation than a single split, plus a standard deviation that tells me how much to trust it. I use it whenever the dataset is small enough that one validation split would be noisy, which is most tabular problems."
        commonMistake="Reporting only the mean CV score. The standard deviation across folds is often the more informative number — a model at 0.85 ± 0.02 is a very different proposition from 0.85 ± 0.11."
        keyTakeaway="K-fold gives you a more stable estimate and an error bar. It replaces the validation set, not the test set."
      />

      <KFoldDiagram />

      <SubHeading priority="must">The variants and when to reach for each</SubHeading>
      <ComparisonTable
        headers={["Variant", "What changes", "Use when"]}
        rows={[
          [
            "K-Fold",
            "Plain random partition into K folds. K = 5 or 10 is standard.",
            "Regression, or classification with balanced classes and no grouping.",
          ],
          [
            "Stratified K-Fold",
            "Each fold preserves the overall class ratio.",
            "Any classification task — mandatory when classes are imbalanced. This is scikit-learn's default for classifiers.",
          ],
          [
            "Group K-Fold",
            "All rows sharing a group id stay in the same fold.",
            "Repeated measurements: multiple visits per patient, multiple sessions per user, multiple photos per person.",
          ],
          [
            "Leave-One-Out (LOOCV)",
            "K = N. Each row is its own validation fold.",
            "Very small datasets (tens of rows). Nearly unbiased, but high-variance and N model fits.",
          ],
          [
            "TimeSeriesSplit",
            "Expanding or rolling window — always train on the past, validate on the future.",
            "Any temporal target. Never shuffle time series.",
          ],
          [
            "Repeated K-Fold",
            "Run K-fold several times with different random seeds and pool the scores.",
            "Small data where a single K-fold estimate is still too noisy.",
          ],
          [
            "Nested CV",
            "An inner loop tunes hyperparameters; an outer loop scores the whole tuning procedure.",
            "When you need an unbiased estimate of a pipeline that includes tuning, and can't spare a test set.",
          ],
        ]}
      />

      <div className="grid gap-3 lg:grid-cols-2">
        <DefinitionCard term="Choosing K">
          <ul className="bullet-list">
            <li>
              <strong>K = 5</strong> — the practical default. Trains on 80% each time, five fits.
            </li>
            <li>
              <strong>K = 10</strong> — slightly less biased (trains on 90%), twice the compute.
            </li>
            <li>
              <strong>Large K</strong> → less bias (training sets are nearly full size), more variance and much more
              compute. LOOCV is the extreme.
            </li>
            <li>
              <strong>Small K</strong> → cheaper, but each model trains on less data so the estimate is
              pessimistically biased.
            </li>
          </ul>
        </DefinitionCard>
        <Callout variant="mistake" title="Time-series CV is not K-fold">
          <p className="mb-2">
            Standard K-fold trains on future folds to predict past ones. Use an expanding window instead:
          </p>
          <Formula>{`fold 1: train 1..100 → test 101..120
fold 2: train 1..120 → test 121..140
fold 3: train 1..140 → test 141..160`}</Formula>
          <p className="mt-2">
            Add a gap between train and test if your features use a lookback window, so the windows can't overlap.
          </p>
        </Callout>
      </div>

      <SubHeading>Interview questions</SubHeading>
      <div className="space-y-2">
        <InterviewQuestion
          qa={{
            id: "cv1",
            q: "If you're using cross-validation, do you still need a test set?",
            short: "Yes — if you used CV to make any decision. CV replaces the validation set, not the test set.",
            strong:
              "Cross-validation is how I choose things: hyperparameters, features, model family. The moment I select the configuration with the best CV score, that score is optimistically biased, because I picked the winner of a search partly on noise. So I keep a test set that never entered the CV loop, and I touch it once at the very end. The exception is when I truly make no selection at all — a single pre-specified model, no tuning — in which case the CV score is a legitimate estimate. That's rare. And if the dataset is too small to spare a test set, the principled alternative is nested cross-validation, where an outer loop scores the entire tune-and-fit procedure rather than a single chosen model.",
            deeper:
              "The distinction people miss: CV estimates the performance of a **procedure** (this pipeline, tuned this way, on this much data). A test set estimates the performance of **the specific fitted model you're about to deploy**. Both are useful, and they answer different questions.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "cv2",
            q: "Your 5-fold CV scores are 0.91, 0.62, 0.88, 0.90, 0.87. What's going on?",
            short: "One fold is badly out of line. That's a data-structure problem, not a modelling problem.",
            strong:
              "A single outlying fold points at something structural. My checklist: is there a grouping the split ignored, so one fold happens to contain an entity the others don't? Is there a time ordering, so one fold covers an unusual period — a promotion, an outage, a policy change? Is the class distribution unbalanced across folds, which stratification would fix? Is the dataset small enough that one fold caught most of the rare class? I'd print the class balance and key feature distributions per fold, which usually makes it obvious immediately. What I would not do is average it out and report 0.836 — the spread is the finding.",
          }}
        />
        <InterviewQuestion
          qa={{
            id: "cv3",
            q: "Why is leave-one-out cross-validation not the obvious best choice?",
            short: "It's expensive, and its estimate has high variance because the N training sets are almost identical to each other.",
            strong:
              "LOOCV has low bias — each model trains on N−1 rows, essentially the full dataset. But the N fitted models are nearly identical, so their errors are highly correlated, and averaging correlated quantities doesn't reduce variance the way averaging independent ones does. You also pay for N model fits. For most problems 5- or 10-fold hits a better bias-variance-compute point. LOOCV earns its place on genuinely tiny datasets where you can't afford to hold out 20%.",
          }}
        />
      </div>

      <Callout variant="memorize">
        <div className="flex flex-wrap gap-2">
          <Chip tone="accent">Classification → StratifiedKFold</Chip>
          <Chip tone="accent">Repeated entities → GroupKFold</Chip>
          <Chip tone="accent">Time → TimeSeriesSplit</Chip>
          <Chip tone="accent">Tiny data → LOOCV or RepeatedKFold</Chip>
          <Chip tone="accent">Need an unbiased tuned estimate → Nested CV</Chip>
        </div>
      </Callout>
    </>
  );
}
